module.exports = {
  angular:{
    src:[
      'angular/js/app.src.js'
    ],
    dest:'angular/js/app.min.js'
  },
  material:{
    src:[
      'material/js/app.src.js'
    ],
    dest:'material/js/app.min.js'
  },  
  html:{
    src:[
      'html/js/app.src.js'
    ],
    dest:'static/js/app.min.js'
  }
}
